# force run: 1
dist: xenial
script: true
stages:
  - name: Publish Web Site
    if: branch = master AND type = push
jobs:
  include:
    - stage: Publish Web Site
      name: Publish Web Site to the www.rtpproxy.org
      script:
        - sh -x deploy.sh
